version: "3.9"

services:
  caddy:
    image: caddy:2.6.2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${PWD}/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "${PWD}/certs/:/test/certs/"
    networks:
      - network

  srv:
    image: registry.gitlab.com/fivegen/clean-city/https-playground
    build: .
    environment:
      - SSL=false
    networks:
      - network

networks:
  network:
    driver: bridge